WebApplication/ViewModels/AboutViewModel.cs
namespace WebApplication.ViewModels
{
    public class AboutViewModel
    {
        public string Link { get; set; }
    }
}

WebApplication/ViewModels/CreateTodoViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WebApplication.ViewModels
{
    public class CreateTodoViewModel
    {
        [Required]
        public string Title { get; set; }
    }
}

WebApplication/ViewModels/DeleteTodoViewModel.cs
using System.ComponentModel.DataAnnotations;
using System;

namespace WebApplication.ViewModels
{
    public class DeleteTodoViewModel
    {
        [Required]
        public Guid? Id { get; set; }
    }
}

WebApplication/ViewModels/HomeViewModel.cs
namespace WebApplication.ViewModels
{
    public class HomeViewModel
    {
        public string Title { get; set; }
        public int ViewsCount { get; set; }
    }
}

WebApplication/ViewModels/TodoViewModel.cs
using System;

namespace WebApplication.ViewModels
{
    public class TodoViewModel
    {
        public Guid Id { get; set; }
        public string Title { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}

WebApplication/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using System.Threading.Tasks;
using WebApplication.Infrastructure.Models;
using WebApplication.Infrastructure;
using WebApplication.Settings;
using WebApplication.ViewModels;

namespace WebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly PageSettings _settings;

        public HomeController(ApplicationContext context, IOptions<PageSettings> settings)
        {
            _context = context;
            _settings = settings.Value;
        }

        public async Task<ViewResult> Index()
        {
            var pageView = await _context.PageViews.FirstOrDefaultAsync(p => p.Name == "Home");
            if (pageView is null)
            {
                pageView = new PageView {Name = "Home"};
                _context.PageViews.Add(pageView);
            }

            pageView.Count++;

            await _context.SaveChangesAsync();
            
            return View(new HomeViewModel
            {
                Title = _settings.Title,
                ViewsCount = pageView.Count
            });
        }

        public ViewResult About()
        {
            return View(new AboutViewModel
            {
                Link = Url.ActionLink(nameof(Index))
            });
        }
    }
}

WebApplication/Controllers/TodosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using System;
using WebApplication.Infrastructure.Models;
using WebApplication.Infrastructure;
using WebApplication.ViewModels;

namespace WebApplication.Controllers
{
    public class TodosController : Controller
    {
        private readonly ApplicationContext _context;

        public TodosController(ApplicationContext context)
        {
            _context = context;
        }

        public async Task<ViewResult> Index()
        {
            var todos = await _context.Todos
                .OrderByDescending(t => t.CreatedAt)
                .Select(t => new TodoViewModel
                {
                    Id = t.Id,
                    Title = t.Title,
                    CreatedAt = t.CreatedAt
                })
                .ToListAsync();

            return View(todos);
        }

        [HttpPost]
        public async Task<RedirectToActionResult> Create([FromForm] CreateTodoViewModel model)
        {
            if (!ModelState.IsValid)
            {
                TempData["Message"] = ModelState.Values.SelectMany(e => e.Errors).FirstOrDefault()?.ErrorMessage;
                return RedirectToAction(nameof(Index));
            }

            var todo = new Todo
            {
                Id = Guid.NewGuid(),
                Title = model.Title,
                CreatedAt = DateTime.UtcNow
            };

            await _context.AddAsync(todo);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        
        [HttpPost]
        public async Task<RedirectToActionResult> Delete([FromForm] DeleteTodoViewModel model)
        {
            if (!ModelState.IsValid)
            {
                TempData["Message"] = ModelState.Values.SelectMany(e => e.Errors).FirstOrDefault()?.ErrorMessage;
                return RedirectToAction(nameof(Index));
            }

            var todo = await _context.Todos.FirstOrDefaultAsync(t => t.Id == model.Id);
            if (todo is null)
            {
                return RedirectToAction(nameof(Index));
            }

            _context.Todos.Remove(todo);
            await _context.SaveChangesAsync();
            
            return RedirectToAction(nameof(Index));
        }
    }
}

WebApplication/Views/Home/About.cshtml
@model AboutViewModel

@{ ViewBag.Title = "About"; }

<div>
    <h1>About</h1>
    <a href="@Model.Link">Home</a>
</div>

WebApplication/Views/Home/Index.cshtml
@model HomeViewModel

@{ ViewBag.Title = "Home"; }

<div>
    <h1>Page views: @Model.ViewsCount</h1>
    <h2>Text: @Model.Title</h2>
    <a asp-action="Index" asp-controller="Todos">Todos</a>
    <a asp-action="About">About</a>
</div>

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewBag.Title</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            width: 100vw;
            height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
        }
        
        h1 {
            margin: 0;
            padding: 0;
        }
        
        div {
            text-align: center;
        }
    </style>
</head>
<body>
@RenderBody()
</body>
</html>

WebApplication/Views/Todos/Index.cshtml
@model IEnumerable<TodoViewModel>

@{ ViewBag.Title = "Todos"; }

<div>
    @if (TempData.ContainsKey("Message"))
    {
        <div style="color: red">@TempData["Message"]</div>
    }
    <h1>Todos</h1>
    <table>
        <thead>
        <tr>
            <th>Title</th>
            <th>Date</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var todo in @Model)
        {
            <tr>
                <td>@todo.Title</td>
                <td>@todo.CreatedAt.ToLongTimeString()</td>
                <td>
                    <form method="POST" asp-action="Delete">
                        <input type="hidden" name="Id" value="@todo.Id" />
                        <button>Complete</button>
                    </form>
                </td>
            </tr>
        }
        </tbody>
    </table>
    <form method="POST" asp-action="Create">
        <input placeholder="Title" name="Title" />
        <button>Create</button>
    </form>
    <a asp-action="Index" asp-controller="Home">Home</a>
    <a asp-action="About" asp-controller="Home">About</a>
</div>